# Generated by Django 5.1.1 on 2024-09-23 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('yandex', 'yandex.ru'), ('gmail', 'gmail.com'), ('mail', 'mail.ru')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True, null=True)),
                ('send_date', models.DateTimeField()),
                ('receive_date', models.DateTimeField(auto_now_add=True)),
                ('message_body', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, null=True)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmailMessage.emailaccount')),
            ],
        ),
    ]
