# Generated by Django 5.1.1 on 2024-09-23 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailMessage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailaccount',
            options={'verbose_name': 'Email account', 'verbose_name_plural': 'Email accounts'},
        ),
        migrations.AlterModelOptions(
            name='emailmessage',
            options={'verbose_name': 'Email message', 'verbose_name_plural': 'Email messages'},
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='password',
            field=models.CharField(max_length=255, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='provider',
            field=models.CharField(choices=[('yandex.ru', 'yandex.ru'), ('gmail.com', 'gmail.com'), ('mail.ru', 'mail.ru')], max_length=50, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='attachments',
            field=models.JSONField(blank=True, null=True, verbose_name='attachments'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='email_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmailMessage.emailaccount', verbose_name='email name'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='message_body',
            field=models.TextField(blank=True, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='receive_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='receive date'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='subject',
            field=models.TextField(blank=True, null=True, verbose_name='subject'),
        ),
    ]
